let masterFields = {
    countyCode: "01",
    countyName: "Adams",
    countyStreetAddress: "200 S 3rd St",
    countyCity: "West Union",
    countyState: "IA",
    countyZip: "52175",
    auditorFirstName: "Jill",
    auditorLastName: "Smith",
    auditorStreetAddress: "200 S 3rd St",
    auditorCity: "West Union",
    auditorState: "IA",
    auditorZip: "52175",
    auditorPhone: "563-422-1234",
    auditorEmail: "jsmith@gmail.com",
    treasurerFirstName: "John",
    treasurerLastName: "Doe",
    treasurerStreetAddress: "200 S 3rd St",
    treasurerCity: "West Union",
    treasurerState: "IA",
    treasurerZip: "52175",
    treasurerPhone: "563-422-1234",
    treasurerEmail: "jdoe@gmail.com",
    attorneyFirstName: "Bobcat",
    attorneyLastName: "Jones",
    attorneyPhone: "563-422-1234",
    attorneyEmail: "Bjones@gmail.com",
    attorneyStreetAddress: "200 S 3rd St",
    attorneyCity: "West Union",
    attorneyState: "IA",
    attorneyZip: "52175",
    assessorFirstName: "Mike",
    assessorLastName: "Davis",
    assessorPhone: "563-422-1234",
    assessorEmail: "mdavis@gmail.com",
    assessorStreetAddress: "200 S 3rd St",
    assessorCity: "West Union",
    assessorState: "IA",
    assessorZip: "52175",
    commissioner1FirstName: "Michael",
    commissioner1LastName: "Johnson",
    commissioner1Phone: "563-422-1234",
    commissioner1Email: "md@sdasd.net",
    commissioner1StreetAddress: "200 S 3rd St",
    commissioner1City: "West Union",
    commissioner1State: "IA",
    commissioner1Zip: "52175",
    commissioner2FirstName: "Griffin",
    commissioner2LastName: "Anderson",
    commissioner2Phone: "563-422-1234",
    commissioner2Email: "yes@no.com",
    commissioner2StreetAddress: "200 S 3rd St",
    commissioner2City: "West Union",
    commissioner2State: "IA",
    commissioner2Zip: "52175",
    commissioner3FirstName: "David",
    commissioner3LastName: "Reed",
    commissioner3Phone: "563-422-1234",
    commissioner3Email: "1234@4543.edu",
    commissioner3StreetAddress: "200 S 3rd St",
    commissioner3City: "West Union",
    commissioner3State: "IA",
    commissioner3Zip: "52175",
    courtHouseName: "Adams County Courthouse",
    courtSteetAddress: "200 S 3rd St",
    courtCity: "West Union",
    courtState: "IA",
    courtZip: "52175",
    courtType: "Circuit",
    clerkFirstName: "John",
    clerkLastName: "Doe",
    clerkPhone: "563-422-1234",
    clerkEmail: "clerk@hellokitty.org",
    clerkStreetAddress: "200 S 3rd St",
    clerkCity: "West Union",
    clerkState: "IA",
    clerkZip: "52175",
    compSys: "LOW",
    countyWebUrl: "www.adamscounty.org",
    presidingJudgeFirstName: "Albert",
    presidingJudgeLastName: "Smith",
    presidingJudgePhone: "563-422-1234",
    presidingJudgeEmail: "judge@judgeymcjudge.gov",
    newspaper1Name: "West Union Times",
    newspaper1ContactFirstName: "Zach",
    newspaper1ContactLastName: "Wylde", 
    newspaper1Phone: "563-422-1234",
    newspaper1AdFormat: "Full Page",
    newspaper1LeadTime: "2 Weeks",
    newspaper1DayAdRuns: "Monday",
    newspaper1URL: "www.westuniontimes.com",
    saleMethod: "Online",
    salestartdatetime: "2023-01-01T12:43:44",
    saleenddatetime: "2023-05-01T14:04:03",
    saleStreetAddress: "Online - Zeus",
    saleCity: "Online - Zeus",
    saleState: "Online - Zeus",
    saleZip: "Online - Zeus",
    sheriffFirstName: "Jane",
    sheriffLastName: "Doe",
    sheriffPhone: "563-422-1234",
    sheriffEmail: "jd@iamlaw.ru",
    sheriffStreetAddress: "200 S 3rd St",
    sheriffCity: "West Union",
    sheriffState: "IA",
    sheriffZip: "52175",
    sheriffAddContactFirstName: "John",
    sheriffAddContactLastName: "Doe",
    sheriffAddContactTitle: "Deputy",
    sheriffAddContactOrganization: "Sheriff's Office",
    sheriffAddContactPhone: "563-422-1234",
    sheriffAddContactEmail: "depbigguy@hellokitty.net",
    sheriffAddContactStreetAddress: "200 S 3rd St",
    sheriffAddContactCity: "West Union",
    sheriffAddContactState: "IA",
    sheriffAddContactZip: "52175",
    paymentStreetAddress: "200 S 3rd St",
    paymentCity: "West Union",
    paymentState: "IA",
    paymentZip: "52175",
    paymentCutoffDateTime: "2023-01-01T12:43:44",
    unsoldBatch: "",
    dynamicEnding: "",
    numBatches: "",
    unsoldStartBatch: "",
    unsoldEndBatch: "",
    withinMinutes: "",
    extendMinutes: "",
  }

const getStates = "SELECT * FROM states ORDER BY name ASC";
const getCounties = "SELECT * FROM counties ORDER BY name ASC";

// add county info to the county data table

















module.exports = { getStates, seedStates}